### Imports and Information:

Healthco Medical Solutions (Not a real company) is planning on opening new healthcare facilities across the United States. They have assigned a team of data analysts and market researchers to investigate the demand for specific healthcare facilities in certain areas. For my part, I have been assigned to evaluate the demand for Hospice Care facilities and Skilled Nursing facilities.

In [1]:
!pip install beautifulsoup4

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import json
import warnings
import requests
import glob
from bs4 import BeautifulSoup
warnings.filterwarnings("ignore")

Requirement already satisfied: beautifulsoup4 in c:\users\hayde\appdata\local\programs\python\python312\lib\site-packages (4.13.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\hayde\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: typing-extensions in c:\users\hayde\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4) (4.12.2)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
df_medicare_benes = pd.read_csv('C:/Users/hayde/Downloads/Hospice+SNF/Medicare Monthly Enrollment Data_October 2025.zip')

In [3]:
df_snf_facility = pd.read_csv('C:/Users/hayde/Downloads/Hospice+SNF/NH_ProviderInfo_May2026.csv')

In [4]:
df_hospice_facility = pd.read_csv('C:/Users/hayde/Downloads/Hospice+SNF/Hospice_General-Information_May2026.csv')

In [5]:
folder1 = "C:/Users/hayde/Downloads/Hospice+SNF/Hospice"
filenames = glob.glob(folder1 + '/*.csv')
df_hospice_enrollments = pd.concat([pd.read_csv(f, encoding='latin-1') for f in filenames], ignore_index = True)

In [6]:
folder2 = 'C:/Users/hayde/Downloads/Hospice+SNF/SNF'
filenames = glob.glob(folder2 + '/*.csv')
df_snf_enrollments = pd.concat([pd.read_csv(f, encoding='latin-1') for f in filenames], ignore_index = True)

I have imported 3 different datasets. In the following cells, I will be stripping them of unessecary data and cleaning what remains. They will be merged into a data model later in Power BI.

### Beneficiary Table Preprocessing

Let's start with a Medicare beneficiary table. This will be the main population sample that I use, because Medicare beneficiaries are more likely to show demand for hospice care and skilled nursing than just raw population.

In [7]:
df_medicare_benes.head()

,YEAR,MONTH,BENE_GEO_LVL,BENE_STATE_ABRVTN,BENE_STATE_DESC,BENE_COUNTY_DESC,BENE_FIPS_CD,TOT_BENES,ORGNL_MDCR_BENES,MA_AND_OTH_BENES,...,B_TOT_BENES,B_ORGNL_MDCR_BENES,B_MA_AND_OTH_BENES,PRSCRPTN_DRUG_TOT_BENES,PRSCRPTN_DRUG_PDP_BENES,PRSCRPTN_DRUG_MAPD_BENES,PRSCRPTN_DRUG_DEEMED_ELIGIBLE_FULL_LIS_BENES,PRSCRPTN_DRUG_FULL_LIS_BENES,PRSCRPTN_DRUG_PARTIAL_LIS_BENES,PRSCRPTN_DRUG_NO_LIS_BENES
0,2013,Year,National,US,National,Total,,52425659,37613096,14812563,...,47959444,33147099,14812345,35679758,22661451,13018307,10000861,1030113.0,409204.0,24239580
1,2013,Year,State,AL,Alabama,Total,01,921477.0,711448.0,210029.0,...,862992.0,652965.0,210026.0,637247.0,437749.0,199498.0,205496.0,32790.0,11452.0,387510.0
2,2013,Year,County,AL,Alabama,Autauga County,01001,9323.0,6484.0,2840.0,...,8742.0,5902.0,2840.0,6036.0,3268.0,2767.0,1839.0,296.0,105.0,3796.0
3,2013,Year,County,AL,Alabama,Baldwin County,01003,41033.0,28775.0,12258.0,...,38651.0,26393.0,12258.0,27352.0,15593.0,11759.0,5276.0,867.0,379.0,20830.0
4,2013,Year,County,AL,Alabama,Barbour County,01005,5847.0,5036.0,810.0,...,5515.0,4704.0,810.0,4170.0,3410.0,759.0,1783.0,304.0,73.0,2009.0

In [8]:
df_medicare_benes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553747 entries, 0 to 553746
Data columns (total 60 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   YEAR                                          553747 non-null  int64
 1   MONTH                                         553747 non-null  object
 2   BENE_GEO_LVL                                  553747 non-null  object
 3   BENE_STATE_ABRVTN                             553747 non-null  object
 4   BENE_STATE_DESC                               553747 non-null  object
 5   BENE_COUNTY_DESC                              553747 non-null  object
 6   BENE_FIPS_CD                                  553747 non-null  object
 7   TOT_BENES                                     553747 non-null  object
 8   ORGNL_MDCR_BENES                              553747 non-null  object
 9   MA_AND_OTH_BENES                              553747 non-null  object
 10  AGED_TOT_BENES                                553747 non-null  object
 11  AGED_ESRD_BENES                               553747 non-null  object
 12  AGED_NO_ESRD_BENES                            553747 non-null  object
 13  DSBLD_TOT_BENES                               553747 non-null  object
 14  DSBLD_ESRD_AND_ESRD_ONLY_BENES                553747 non-null  object
 15  DSBLD_NO_ESRD_BENES                           553747 non-null  object
 16  MALE_TOT_BENES                                553747 non-null  object
 17  FEMALE_TOT_BENES                              553747 non-null  object
 18  WHITE_TOT_BENES                               553747 non-null  object
 19  BLACK_TOT_BENES                               553747 non-null  object
 20  API_TOT_BENES                                 553747 non-null  object
 21  HSPNC_TOT_BENES                               553747 non-null  object
 22  NATIND_TOT_BENES                              553747 non-null  object
 23  OTHR_TOT_BENES                                553747 non-null  object
 24  AGE_LT_25_BENES                               553747 non-null  object
 25  AGE_25_TO_44_BENES                            553747 non-null  object
 26  AGE_45_TO_64_BENES                            553747 non-null  object
 27  AGE_65_TO_69_BENES                            553747 non-null  object
 28  AGE_70_TO_74_BENES                            553747 non-null  object
 29  AGE_75_TO_79_BENES                            553747 non-null  object
 30  AGE_80_TO_84_BENES                            553747 non-null  object
 31  AGE_85_TO_89_BENES                            553747 non-null  object
 32  AGE_90_TO_94_BENES                            553747 non-null  object
 33  AGE_GT_94_BENES                               553747 non-null  object
 34  DUAL_TOT_BENES                                553747 non-null  object
 35  FULL_DUAL_TOT_BENES                           553747 non-null  object
 36  PART_DUAL_TOT_BENES                           553747 non-null  object
 37  NODUAL_TOT_BENES                              553747 non-null  object
 38  QMB_ONLY_BENES                                553747 non-null  object
 39  QMB_PLUS_BENES                                553747 non-null  object
 40  SLMB_ONLY_BENES                               553747 non-null  object
 41  SLMB_PLUS_BENES                               553747 non-null  object
 42  QDWI_QI_BENES                                 553747 non-null  object
 43  OTHR_FULL_DUAL_MDCD_BENES                     553747 non-null  object
 44  A_B_TOT_BENES                                 553747 non-null  object
 45  A_B_ORGNL_MDCR_BENES                          553747 non-null  object
 46  A_B_MA_AND_OTH_BENES                          553747 non-null  object
 47  A_TOT_BENES                                   553747 non-null  object
 48  A_ORGNL_MDCR_BENES                            553747 non-null  object
 49  A_MA_AND_OTH_BENES                            553747 non-null  object
 50  B_TOT_BENES                                   553747 non-null  object
 51  B_ORGNL_MDCR_BENES                            553747 non-null  object
 52  B_MA_AND_OTH_BENES                            553747 non-null  object
 53  PRSCRPTN_DRUG_TOT_BENES                       553747 non-null  object
 54  PRSCRPTN_DRUG_PDP_BENES                       553747 non-null  object
 55  PRSCRPTN_DRUG_MAPD_BENES                      553747 non-null  object
 56  PRSCRPTN_DRUG_DEEMED_ELIGIBLE_FULL_LIS_BENES  553747 non-null  object
 57  PRSCRPTN_DRUG_FULL_LIS_BENES                  553747 non-null  object
 58  PRSCRPTN_DRUG_PARTIAL_LIS_BENES               553747 non-null  object
 59  PRSCRPTN_DRUG_NO_LIS_BENES                    553747 non-null  object
dtypes: int64(1), object(59)
memory usage: 253.5+ MB

This is a big dataframe, but I only need a small subset. I need to filter out all the total beneficary summary entries for 2025 partitioned by state to match the other datasets. I also need the state abbreviation so it can be connected to the rest of the data Power BI. I've chosen October because the data contains snapshots of the month to month transactions, and Medicare beneficiaries have almost unnoticeable month to month changes.

In [9]:
df_medicare_benes2 = df_medicare_benes[
    (df_medicare_benes['YEAR'] == 2025) &
    (df_medicare_benes['MONTH'] == 'October') &
    (df_medicare_benes['BENE_GEO_LVL'] == 'State')
][['YEAR','BENE_STATE_ABRVTN', 'BENE_STATE_DESC', 'TOT_BENES']]

df_medicare_benes2.head()

        YEAR BENE_STATE_ABRVTN BENE_STATE_DESC  TOT_BENES
550411  2025                AL         Alabama  1133045.0
550480  2025                AK          Alaska   121911.0
550512  2025                AZ         Arizona  1536462.0
550529  2025                AR        Arkansas   687541.0
550606  2025                CA      California  7130161.0

I only took October because the enrollment data is a record of the number of Medicare Beneficiaries that month including new enrollees, not the raw new enrollees. If I took every month, it's like multiplying the total beneficiaries for a state x 12. Also, the 2025 data only goes up to October. The best way to get the most accurate data was to get the latest month in 2025.

In [10]:
df_medicare_benes2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 550411 to 553746
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   YEAR               58 non-null     int64
 1   BENE_STATE_ABRVTN  58 non-null     object
 2   BENE_STATE_DESC    58 non-null     object
 3   TOT_BENES          58 non-null     object
dtypes: int64(1), object(3)
memory usage: 2.3+ KB

In [11]:
df_medicare_benes2['TOT_BENES'] = pd.to_numeric(df_medicare_benes2['TOT_BENES'], errors = 'coerce')
df_medicare_benes2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 550411 to 553746
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   YEAR               58 non-null     int64
 1   BENE_STATE_ABRVTN  58 non-null     object
 2   BENE_STATE_DESC    58 non-null     object
 3   TOT_BENES          57 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 2.3+ KB

We lost an entry, I'd like to know what it is.

In [12]:
df_medicare_benes2[df_medicare_benes2['TOT_BENES'].isnull()][['BENE_STATE_ABRVTN', 'TOT_BENES']]

       BENE_STATE_ABRVTN  TOT_BENES
553745                UK        NaN

Since info from the UK apparantly wasn't present in the dataset and isn't part of the analysis, I will proceed.

In [13]:
df_medicare_benes3 = df_medicare_benes2.groupby(['BENE_STATE_ABRVTN', 'BENE_STATE_DESC', 'YEAR'])['TOT_BENES'].sum().reset_index()

In [14]:
df_medicare_benes3.head()

  BENE_STATE_ABRVTN BENE_STATE_DESC  YEAR  TOT_BENES
0                AK          Alaska  2025   121911.0
1                AL         Alabama  2025  1133045.0
2                AR        Arkansas  2025   687541.0
3                AS  American Samoa  2025     4949.0
4                AZ         Arizona  2025  1536462.0

In [15]:
df_medicare_benes3.nunique()

BENE_STATE_ABRVTN    58
BENE_STATE_DESC      58
YEAR                  1
TOT_BENES            58
dtype: int64

Oh, that's odd. The United States only has 50 states and yet we have 58 entries. Accounting for the UK thing it should be 51, but let's see here...

In [16]:
df_medicare_benes3['BENE_STATE_ABRVTN'].unique()

array(['AK', 'AL', 'AR', 'AS', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL',
       'FO', 'GA', 'GU', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA',
       'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MP', 'MS', 'MT', 'NC', 'ND',
       'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR',
       'RI', 'SC', 'SD', 'TN', 'TX', 'UK', 'UT', 'VA', 'VI', 'VT', 'WA',
       'WI', 'WV', 'WY'], dtype=object)

It appears we have a few non-mainland territories in the data. Healthco only requested I look at the main 50 States, so I'll remove these to avoid excess data.

In [17]:
subset = ['DC', 'AS', 'GU', 'MP', 'PR', 'VI', 'UK', 'FO']

df_medicare_benes4 = df_medicare_benes3[~df_medicare_benes3['BENE_STATE_ABRVTN'].isin(subset)]
df_medicare_benes4.nunique()

BENE_STATE_ABRVTN    50
BENE_STATE_DESC      50
YEAR                  1
TOT_BENES            50
dtype: int64

There we go. Now I'll just do a quick duplicate check...

In [18]:
df_medicare_benes4.duplicated().sum() #No duplicates, yay~

0

Lastly, I'll tweak the state column name.

In [19]:
df_medicare_benes4 = df_medicare_benes4.rename(columns = {'BENE_STATE_ABRVTN': 'STATE_ABV'})

### Population Table Preprocessing

I'll be using the Medicare Beneficiary count for distribution ratios, but I wanted the raw population data on file for comparison. The specific population table I want isn't simply in a csv file, it's on a Wikipedia page and therefore needs to be scraped. Pandas has a built in mechanism for simple scrapes, so I'll try that first.

In [20]:
url = 'https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_population'
headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers = headers)

tables = pd.read_html(response.text)
len(tables)

7

In [21]:
df_state_population = tables[1]
df_state_population.head()

  Unnamed: 0_level_0 State or territory Census population[8][9][a]  \
  Unnamed: 0_level_1 State or territory        July 1, 2025 (est.)
0                  1         California                 39355309.0
1                  2              Texas                 31709821.0
2                  3            Florida                 23462518.0
3                  4           New York                 20002427.0
4                  5       Pennsylvania                 13059432.0

                House seats[b]         Pop. per elec. vote (2020)[c]  \
  April 1, 2020          Seats       % Pop. per elec. vote (2020)[c]
0      39538223             52  11.95%                        732189
1      29145505             38   8.74%                        728638
2      21538187             28   6.44%                        717940
3      20201249             26   5.98%                        721473
4      13002700             17   3.91%                        684353

  Pop. per seat (2020)[a] % US (2020) % EC (2020)
  Pop. per seat (2020)[a] % US (2020) % EC (2020)
0                  760350     11.800%      10.04%
1                  766987      8.698%       7.43%
2                  769221      6.428%       5.58%
3                  776971      6.029%       5.20%
4                  764865      3.881%       3.53%

The scrape was successful, but the formatting is messy. There's an extra header that was kept from the original webpage. Let's fix that.

In [22]:
df_state_population.columns = df_state_population.columns.get_level_values(1)
df_state_population.head()

,Unnamed: 0_level_1,State or territory,"July 1, 2025 (est.)","April 1, 2020",Seats,%,Pop. per elec. vote (2020)[c],Pop. per seat (2020)[a],% US (2020),% EC (2020)
0,1,California,39355309.0,39538223,52,11.95%,732189,760350,11.800%,10.04%
1,2,Texas,31709821.0,29145505,38,8.74%,728638,766987,8.698%,7.43%
2,3,Florida,23462518.0,21538187,28,6.44%,717940,769221,6.428%,5.58%
3,4,New York,20002427.0,20201249,26,5.98%,721473,776971,6.029%,5.20%
4,5,Pennsylvania,13059432.0,13002700,17,3.91%,684353,764865,3.881%,3.53%

In [23]:
df_state_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0_level_1             56 non-null     object
 1   State or territory             60 non-null     object
 2   July 1, 2025 (est.)            55 non-null     float64
 3   April 1, 2020                  60 non-null     int64
 4   Seats                          60 non-null     object
 5   %                              60 non-null     object
 6   Pop. per elec. vote (2020)[c]  60 non-null     object
 7   Pop. per seat (2020)[a]        60 non-null     object
 8   % US (2020)                    60 non-null     object
 9   % EC (2020)                    60 non-null     object
dtypes: float64(1), int64(1), object(8)
memory usage: 4.8+ KB

Now I'll drop some of the unessecary columns. I don't need a lot from this dataset.

In [24]:
cols = ['State or territory', 'July 1, 2025 (est.)']

df_state_population2 = df_state_population[cols]

df_state_population2.head()

  State or territory  July 1, 2025 (est.)
0         California           39355309.0
1              Texas           31709821.0
2            Florida           23462518.0
3           New York           20002427.0
4       Pennsylvania           13059432.0

I also need to add in the abbreviations so the datasets can be conneted in Power BI.

In [25]:
us_state_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY"
}

df_state_population2["state_abbrev"] = df_state_population2["State or territory"].map(us_state_abbrev)

df_state_population2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State or territory   60 non-null     object
 1   July 1, 2025 (est.)  55 non-null     float64
 2   state_abbrev         50 non-null     object
dtypes: float64(1), object(2)
memory usage: 1.5+ KB

I'll tweak the column names to make them more harmonious with the data.

In [26]:
df_state_population3 = df_state_population2.rename(columns = {'State or territory': 'STATE', 'July 1, 2025 (est.)': 'POPULATION', 'state_abbrev': 'STATE_ABV'})
df_state_population3.head()

          STATE  POPULATION STATE_ABV
0    California  39355309.0        CA
1         Texas  31709821.0        TX
2       Florida  23462518.0        FL
3      New York  20002427.0        NY
4  Pennsylvania  13059432.0        PA

In [27]:
df_state_population3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATE       60 non-null     object
 1   POPULATION  55 non-null     float64
 2   STATE_ABV   50 non-null     object
dtypes: float64(1), object(2)
memory usage: 1.5+ KB

Now let's check the duplicated values in the population table.

In [28]:
df_state_population3.duplicated().sum() #No duplicates. Yay~

0

Now let's check the missing values in the population table.

In [29]:
df_state_population3[df_state_population3['POPULATION'].isnull()]

                           STATE  POPULATION STATE_ABV
52                      Guam[11]         NaN       NaN
53       U.S. Virgin Islands[12]         NaN       NaN
54            American Samoa[13]         NaN       NaN
55  Northern Mariana Islands[14]         NaN       NaN
59      Total US and territories         NaN       NaN

In [30]:
df_state_population3[df_state_population3['STATE_ABV'].isnull()]

                           STATE   POPULATION STATE_ABV
32                   Puerto Rico    3184835.0       NaN
49          District of Columbia     693645.0       NaN
52                      Guam[11]          NaN       NaN
53       U.S. Virgin Islands[12]          NaN       NaN
54            American Samoa[13]          NaN       NaN
55  Northern Mariana Islands[14]          NaN       NaN
56      Contiguous United States  339614767.0       NaN
57                 The 50 states  341091212.0       NaN
58        The 50 states and D.C.  341784857.0       NaN
59      Total US and territories          NaN       NaN

It appears the missing values without population records or abbreviations from the map are US territories not in the United States, which I'm not targeting for this analysis. They can be comfortably dropped.

In [31]:
df_state_population4 = df_state_population3.dropna()
df_state_population4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 51
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   STATE       50 non-null     object
 1   POPULATION  50 non-null     float64
 2   STATE_ABV   50 non-null     object
dtypes: float64(1), object(2)
memory usage: 1.6+ KB

### Hospice Care Preprocessing

In [32]:
df_hospice_enrollments.head()

,ENROLLMENT ID,ENROLLMENT STATE,PROVIDER TYPE CODE,PROVIDER TYPE TEXT,NPI,MULTIPLE NPI FLAG,CCN,ASSOCIATE ID,ORGANIZATION NAME,DOING BUSINESS AS NAME,...,INCORPORATION STATE,ORGANIZATION TYPE STRUCTURE,ORGANIZATION OTHER TYPE TEXT,PROPRIETARY_NONPROFIT,ADDRESS LINE 1,ADDRESS LINE 2,CITY,STATE,ZIP CODE,DATE
0,O20020813000008,KS,00-08,PART A PROVIDER - HOSPICE,1144260498,N,171523,3274440268,HOSPITAL DISTRICT NO 1 OF DICKINSON COUNTY KANSAS,HOSPICE OF DICKINSON COUNTY,...,KS,OTHER,GOVERNMENTAL,N,1111 N BRADY ST,STE B,ABILENE,KS,674101804,01/2025
1,O20020813000010,PA,00-08,PART A PROVIDER - HOSPICE,1053393447,N,391518,3476461872,"CENTRE HOMECARE, INC.",CENTRE CROSSINGS HOSPICE,...,PA,CORPORATION,NaN,N,2437 COMMERCIAL BLVD,STE 280,STATE COLLEGE,PA,168017454,01/2025
2,O20020820000009,PA,00-08,PART A PROVIDER - HOSPICE,1548201957,N,391551,4789591710,GENERAL CARE SERVICES INC,HOSPICE OF WARREN COUNTY,...,PA,CORPORATION,NaN,N,1 MAIN AVE,NaN,WARREN,PA,163652116,01/2025
3,O20020823000006,OR,00-08,PART A PROVIDER - HOSPICE,1841221306,N,381546,2365359296,MORROW COUNTY HEALTH DISTRICT,PIONEER MEMORIAL HOSPICE,...,OR,OTHER,DISTRICT,N,162 N MAIN ST,NaN,HEPPNER,OR,978365001,01/2025
4,O20020823000007,MO,00-08,PART A PROVIDER - HOSPICE,1215084876,N,261586,2264349109,SAFE HARBOR HOSPICE LLC,"LEGACY OPERATING COMPANY, LLC",...,MO,LLC,NaN,P,101 KINGSBURY BLVD,NaN,FREDERICKTOWN,MO,636457959,01/2025

In [33]:
df_hospice_enrollments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25993 entries, 0 to 25992
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ENROLLMENT ID                 25993 non-null  object
 1   ENROLLMENT STATE              25993 non-null  object
 2   PROVIDER TYPE CODE            25993 non-null  object
 3   PROVIDER TYPE TEXT            25993 non-null  object
 4   NPI                           25993 non-null  int64
 5   MULTIPLE NPI FLAG             25993 non-null  object
 6   CCN                           25993 non-null  object
 7   ASSOCIATE ID                  25993 non-null  int64
 8   ORGANIZATION NAME             25993 non-null  object
 9   DOING BUSINESS AS NAME        13002 non-null  object
 10  INCORPORATION DATE            22914 non-null  object
 11  INCORPORATION STATE           23085 non-null  object
 12  ORGANIZATION TYPE STRUCTURE   25993 non-null  object
 13  ORGANIZATION OTHER TYPE TEXT  897 non-null    object
 14  PROPRIETARY_NONPROFIT         25993 non-null  object
 15  ADDRESS LINE 1                25993 non-null  object
 16  ADDRESS LINE 2                18270 non-null  object
 17  CITY                          25993 non-null  object
 18  STATE                         25993 non-null  object
 19  ZIP CODE                      25993 non-null  int64
 20  DATE                          25993 non-null  object
dtypes: int64(3), object(18)
memory usage: 4.2+ MB

Just like with the population dataset, I'll remove the columns I don't need. Again, this analysis is highly specialized, so I don't need a huge number of excess lookup columns gumming up the space in my data model later.

In [34]:
cols = ['ENROLLMENT ID',
        'ENROLLMENT STATE',
        'NPI',
        'ORGANIZATION TYPE STRUCTURE',
        'ORGANIZATION OTHER TYPE TEXT',
        'PROPRIETARY_NONPROFIT',
        'CITY', 
        'DATE']

df_hospice_enrollments2 = df_hospice_enrollments[cols]

df_hospice_enrollments2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25993 entries, 0 to 25992
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ENROLLMENT ID                 25993 non-null  object
 1   ENROLLMENT STATE              25993 non-null  object
 2   NPI                           25993 non-null  int64
 3   ORGANIZATION TYPE STRUCTURE   25993 non-null  object
 4   ORGANIZATION OTHER TYPE TEXT  897 non-null    object
 5   PROPRIETARY_NONPROFIT         25993 non-null  object
 6   CITY                          25993 non-null  object
 7   DATE                          25993 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.6+ MB

A quick duplicate check...

In [35]:
df_hospice_enrollments2.duplicated().sum() #No duplicates. Yay~

0

Now I'll do a little bit of preprocessing on the physical hospice facility building data.

In [36]:
df_hospice_facility.head()

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Ownership Type,Certification Date
0,001500,AGAVE HOSPICE AND PALLIATIVE CARE,4050 EAST GREENWAY ROAD SUITE 1,NaN,PHOENIX,AZ,85032,Maricopa,(602) 855-3500,9,For-Profit,04/07/2022
1,001502,"FAMILY FIRST HOSPICE, INC",11225 N 28TH DRIVE STE B111,NaN,PHOENIX,AZ,85029,Maricopa,(480) 482-1833,9,For-Profit,03/30/2022
2,001504,"VITAL HC, INC",4447 EAST BROADWAY ROAD SUITE 101,NaN,MESA,AZ,85206,Maricopa,(520) 278-5003,9,For-Profit,06/03/2022
3,001505,ADVOCATE HOSPICE,"7600 NORTH 16TH STREET, SUITE 112",NaN,PHOENIX,AZ,85020,Maricopa,(602) 830-0605,9,For-Profit,05/27/2022
4,001508,OPTIMAL HOSPICE INC,"64 EAST BROADWAY ROAD, SUITE 200 OFFICE 278",NaN,TEMPE,AZ,85282,Maricopa,(623) 887-8837,9,For-Profit,06/22/2022

In [37]:
cols = ['CMS Certification Number (CCN)',
        'Facility Name',
        'City/Town',
        'State',
        'Ownership Type',
        ]

df_hospice_facility2 = df_hospice_facility[cols]

df_hospice_facility2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6852 entries, 0 to 6851
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CMS Certification Number (CCN)  6852 non-null   object
 1   Facility Name                   6852 non-null   object
 2   City/Town                       6852 non-null   object
 3   State                           6852 non-null   object
 4   Ownership Type                  6087 non-null   object
dtypes: object(5)
memory usage: 267.8+ KB

The only column with a missing value is ownership type, which considering context could just as easily mean 'other' I'll leave it alone. Lastly, I'll check duplicates.

In [38]:
df_hospice_facility2.duplicated().sum()

0

### Skilled Nursing Care Preprocessing

For this section I will be repeating most of the code for the hospice care section. If I do something different, I'll document it.

In [39]:
df_snf_enrollments.head()

,ENROLLMENT ID,ENROLLMENT STATE,PROVIDER TYPE CODE,PROVIDER TYPE TEXT,NPI,MULTIPLE NPI FLAG,CCN,ASSOCIATE ID,ORGANIZATION NAME,DOING BUSINESS AS NAME,...,PROPRIETARY_NONPROFIT,NURSING HOME PROVIDER NAME,AFFILIATION ENTITY NAME,AFFILIATION ENTITY ID,ADDRESS LINE 1,ADDRESS LINE 2,CITY,STATE,ZIP CODE,DATE
0,O20020801000000,NC,00-18,PART A PROVIDER - SKILLED NURSING FACILITY,1346210291,N,345500,6103733167,WINDSOR POINT INC.,WINDSOR POINT INC CCRC,...,P,WINDSOR POINT CONTINUING CARE,NaN,NaN,1221 BROAD STREET,NaN,FUQUAY-VARINA,NC,275263602,01/2025
1,O20020805000004,OK,00-18,PART A PROVIDER - SKILLED NURSING FACILITY,1912906694,N,375417,6901713973,N&R OF WESTHAVEN L L C,WESTHAVEN NURSING HOME,...,P,WESTHAVEN NURSING HOME,NaN,NaN,1215 S. WESTERN,WESTERN NURSING HOME,STILLWATER,OK,740745151,01/2025
2,O20020814000007,TN,00-18,PART A PROVIDER - SKILLED NURSING FACILITY,1104838606,N,445316,7012824014,"HILLCREST HEALTHCARE, LLC",HILLCREST HEALTHCARE,...,P,HILLCREST HEALTHCARE CENTER,NaN,NaN,111 PEMBERTON DR,NaN,ASHLAND CITY,TN,370151353,01/2025
3,O20020814000013,TN,00-18,PART A PROVIDER - SKILLED NURSING FACILITY,1477576346,N,445463,2466369467,BELLS NURSING HOME INC,BELLS NURSING AND REHABILITATION CENTER,...,P,BELLS NURSING AND REHABILITATION CENTER,NaN,NaN,213 HERNDON DR,NaN,BELLS,TN,380063654,01/2025
4,O20020816000002,MA,00-18,PART A PROVIDER - SKILLED NURSING FACILITY,1760479851,N,225513,1850208877,BEAUMONT WHITNEY PLACE NORTHBOROUGH,BEAUMONT REHABILITATION & SKILLED NURSING CENT...,...,P,BEAUMONT REHAB & SKILLED NURSING CTR - NORTHBORO,NaN,NaN,238 W MAIN ST,NaN,NORTHBOROUGH,MA,15321804,01/2025

In [40]:
df_snf_enrollments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173463 entries, 0 to 173462
Data columns (total 24 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   ENROLLMENT ID                 173463 non-null  object
 1   ENROLLMENT STATE              173463 non-null  object
 2   PROVIDER TYPE CODE            173463 non-null  object
 3   PROVIDER TYPE TEXT            173463 non-null  object
 4   NPI                           173463 non-null  int64
 5   MULTIPLE NPI FLAG             173463 non-null  object
 6   CCN                           173463 non-null  object
 7   ASSOCIATE ID                  173463 non-null  int64
 8   ORGANIZATION NAME             173463 non-null  object
 9   DOING BUSINESS AS NAME        150003 non-null  object
 10  INCORPORATION DATE            127112 non-null  object
 11  INCORPORATION STATE           128725 non-null  object
 12  ORGANIZATION TYPE STRUCTURE   173463 non-null  object
 13  ORGANIZATION OTHER TYPE TEXT  25944 non-null   object
 14  PROPRIETARY_NONPROFIT         173463 non-null  object
 15  NURSING HOME PROVIDER NAME    169079 non-null  object
 16  AFFILIATION ENTITY NAME       117251 non-null  object
 17  AFFILIATION ENTITY ID         117251 non-null  float64
 18  ADDRESS LINE 1                173463 non-null  object
 19  ADDRESS LINE 2                7987 non-null    object
 20  CITY                          173463 non-null  object
 21  STATE                         173463 non-null  object
 22  ZIP CODE                      173463 non-null  int64
 23  DATE                          173463 non-null  object
dtypes: float64(1), int64(3), object(20)
memory usage: 31.8+ MB

In [41]:
cols = ['ENROLLMENT ID',
        'ENROLLMENT STATE',
        'NPI',
        'ORGANIZATION TYPE STRUCTURE',
        'ORGANIZATION OTHER TYPE TEXT',
        'PROPRIETARY_NONPROFIT',
        'CITY',
        'DATE']

df_snf_enrollments2 = df_snf_enrollments[cols]

df_snf_enrollments2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173463 entries, 0 to 173462
Data columns (total 8 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   ENROLLMENT ID                 173463 non-null  object
 1   ENROLLMENT STATE              173463 non-null  object
 2   NPI                           173463 non-null  int64
 3   ORGANIZATION TYPE STRUCTURE   173463 non-null  object
 4   ORGANIZATION OTHER TYPE TEXT  25944 non-null   object
 5   PROPRIETARY_NONPROFIT         173463 non-null  object
 6   CITY                          173463 non-null  object
 7   DATE                          173463 non-null  object
dtypes: int64(1), object(7)
memory usage: 10.6+ MB

In [42]:
df_snf_enrollments2.duplicated().sum() #No duplicates. Yay~

0

In [43]:
df_snf_facility.head()

,CMS Certification Number (CCN),Provider Name,Provider Address,City/Town,State,ZIP Code,Telephone Number,Provider SSA County Code,County/Parish,Urban,...,Number of Citations from Infection Control Inspections,Number of Fines,Total Amount of Fines in Dollars,Number of Payment Denials,Total Number of Penalties,Location,Latitude,Longitude,Geocoding Footnote,Processing Date
0,015009,"BURNS NURSING HOME, INC.",701 MONROE STREET NW,RUSSELLVILLE,AL,35653,2563324110,290,Franklin,N,...,NaN,0,0.0,0,0,"701 MONROE STREET NW,RUSSELLVILLE,AL,35653",34.5149,-87.736,NaN,2026-05-01
1,015010,COOSA VALLEY HEALTHCARE CENTER,260 WEST WALNUT STREET,SYLACAUGA,AL,35150,2562495604,600,Talladega,N,...,0.0,0,0.0,0,0,"260 WEST WALNUT STREET,SYLACAUGA,AL,35150",33.1637,-86.254,NaN,2026-05-01
2,015012,HIGHLANDS HEALTH AND REHAB,380 WOODS COVE ROAD,SCOTTSBORO,AL,35768,2562183708,350,Jackson,N,...,NaN,0,0.0,0,0,"380 WOODS COVE ROAD,SCOTTSBORO,AL,35768",34.6611,-86.047,NaN,2026-05-01
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206,2058330146,360,Jefferson,Y,...,0.0,0,0.0,0,0,"7755 FOURTH AVENUE SOUTH,BIRMINGHAM,AL,35206",33.5595,-86.722,NaN,2026-05-01
4,015015,PLANTATION MANOR NURSING HOME,6450 OLD TUSCALOOSA HIGHWAY,MC CALLA,AL,35111,2054776161,360,Jefferson,Y,...,NaN,0,0.0,0,0,"6450 OLD TUSCALOOSA HIGHWAY,MC CALLA,AL,35111",33.3222,-87.034,NaN,2026-05-01

In [44]:
cols = ['CMS Certification Number (CCN)',
        'Provider Name',
        'City/Town',
        'State',
        'Ownership Type',
        ]

df_snf_facility2 = df_snf_facility[cols]

df_snf_facility2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14700 entries, 0 to 14699
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CMS Certification Number (CCN)  14700 non-null  object
 1   Provider Name                   14700 non-null  object
 2   City/Town                       14700 non-null  object
 3   State                           14700 non-null  object
 4   Ownership Type                  14700 non-null  object
dtypes: object(5)
memory usage: 574.3+ KB

### Database Creation

In [45]:
!pip install pymysql

import sqlalchemy
import pymysql
from sqlalchemy import create_engine
from sqlalchemy import text

Requirement already satisfied: pymysql in c:\users\hayde\appdata\local\programs\python\python312\lib\site-packages (1.2.0)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [46]:
engine = create_engine('mysql+pymysql://root:B33pb33plettuce!@localhost:3306/hos_snf')

In [47]:
df_state_population4.to_sql(name = 'population', con = engine, if_exists = 'replace', index = False)

with engine.connect() as conn:
  output = conn.execute(text("SELECT * FROM population LIMIT 5")).fetchall()

for row in output:
  print(row)

('California', 39355309.0, 'CA')
('Texas', 31709821.0, 'TX')
('Florida', 23462518.0, 'FL')
('New York', 20002427.0, 'NY')
('Pennsylvania', 13059432.0, 'PA')

In [59]:
df_medicare_benes4.to_sql(name = 'beneficiaries', con = engine, if_exists = 'replace', index = False)

with engine.connect() as conn:
  output = conn.execute(text("SELECT * FROM beneficiaries LIMIT 5")).fetchall()

for row in output:
  print(row)

('AK', 'Alaska', 2025, 121911.0)
('AL', 'Alabama', 2025, 1133045.0)
('AR', 'Arkansas', 2025, 687541.0)
('AZ', 'Arizona', 2025, 1536462.0)
('CA', 'California', 2025, 7130161.0)

In [49]:
df_hospice_enrollments2.to_sql(name = 'hospice_enrollments', con = engine, if_exists = 'replace', index_label = 'Enrollment_No')

with engine.connect() as conn:
  output = conn.execute(text("SELECT * FROM hospice_enrollments LIMIT 5")).fetchall()

for row in output:
  print(row)

(0, 'O20020813000008', 'KS', 1144260498, 'OTHER', 'GOVERNMENTAL', 'N', 'ABILENE', '01/2025')
(1, 'O20020813000010', 'PA', 1053393447, 'CORPORATION', None, 'N', 'STATE COLLEGE', '01/2025')
(2, 'O20020820000009', 'PA', 1548201957, 'CORPORATION', None, 'N', 'WARREN', '01/2025')
(3, 'O20020823000006', 'OR', 1841221306, 'OTHER', 'DISTRICT', 'N', 'HEPPNER', '01/2025')
(4, 'O20020823000007', 'MO', 1215084876, 'LLC', None, 'P', 'FREDERICKTOWN', '01/2025')

In [50]:
df_snf_enrollments2.to_sql(name = 'snf_enrollments', con = engine, if_exists = 'replace', index_label = 'Enrollment_No')

with engine.connect() as conn:
  output = conn.execute(text("SELECT * FROM snf_enrollments LIMIT 5")).fetchall()

for row in output:
  print(row)

(0, 'O20020801000000', 'NC', 1346210291, 'CORPORATION', None, 'P', 'FUQUAY-VARINA', '01/2025')
(1, 'O20020805000004', 'OK', 1912906694, 'LLC', None, 'P', 'STILLWATER', '01/2025')
(2, 'O20020814000007', 'TN', 1104838606, 'LLC', None, 'P', 'ASHLAND CITY', '01/2025')
(3, 'O20020814000013', 'TN', 1477576346, 'CORPORATION', None, 'P', 'BELLS', '01/2025')
(4, 'O20020816000002', 'MA', 1760479851, 'LLC', None, 'P', 'NORTHBOROUGH', '01/2025')

In [51]:
df_hospice_facility2.to_sql(name = 'hospice_facilities', con = engine, if_exists = 'replace', index = False)

with engine.connect() as conn:
  output = conn.execute(text("SELECT * FROM hospice_facilities LIMIT 5")).fetchall()

for row in output:
  print(row)

('001500', 'AGAVE HOSPICE AND PALLIATIVE CARE', 'PHOENIX', 'AZ', 'For-Profit')
('001502', 'FAMILY FIRST HOSPICE, INC', 'PHOENIX', 'AZ', 'For-Profit')
('001504', 'VITAL HC, INC', 'MESA', 'AZ', 'For-Profit')
('001505', 'ADVOCATE HOSPICE ', 'PHOENIX', 'AZ', 'For-Profit')
('001508', 'OPTIMAL HOSPICE INC', 'TEMPE', 'AZ', 'For-Profit')

In [52]:
df_snf_facility2.to_sql(name = 'snf_facilities', con = engine, if_exists = 'replace', index = False)

with engine.connect() as conn:
  output = conn.execute(text("SELECT * FROM snf_facilities LIMIT 5")).fetchall()

for row in output:
  print(row)

('015009', 'BURNS NURSING HOME, INC.', 'RUSSELLVILLE', 'AL', 'For profit - Corporation')
('015010', 'COOSA VALLEY HEALTHCARE CENTER', 'SYLACAUGA', 'AL', 'For profit - Corporation')
('015012', 'HIGHLANDS HEALTH AND REHAB', 'SCOTTSBORO', 'AL', 'Government - County')
('015014', 'EASTVIEW REHABILITATION & HEALTHCARE CENTER', 'BIRMINGHAM', 'AL', 'For profit - Individual')
('015015', 'PLANTATION MANOR NURSING HOME', 'MC CALLA', 'AL', 'For profit - Corporation')

The preprocessing is complete. Now I just need to download the files and import them into Power BI for analysis.

### Data Dictionaries

Normally data dictionaries go at the beginning, but since I'm cleaning and preprocessing more than one dataset and dropping a generous number of columns, I figured it would be better to clean and cut the columns first, and place the dictionary at the end to define what remains.

#### Hospice + SNF Dictionaries

In [53]:
df_hospice_enrollments2.head()

,ENROLLMENT ID,ENROLLMENT STATE,NPI,ORGANIZATION TYPE STRUCTURE,ORGANIZATION OTHER TYPE TEXT,PROPRIETARY_NONPROFIT,CITY,DATE
0,O20020813000008,KS,1144260498,OTHER,GOVERNMENTAL,N,ABILENE,01/2025
1,O20020813000010,PA,1053393447,CORPORATION,NaN,N,STATE COLLEGE,01/2025
2,O20020820000009,PA,1548201957,CORPORATION,NaN,N,WARREN,01/2025
3,O20020823000006,OR,1841221306,OTHER,DISTRICT,N,HEPPNER,01/2025
4,O20020823000007,MO,1215084876,LLC,NaN,P,FREDERICKTOWN,01/2025

ENROLLMENT ID: This is the ID number of the enrollment record. It primarily functions as an index.

ENROLLMENT STATE: This is the state where the recorded enrollment was conducted.

NPI: A unique identifier applying to all enrollments. It functions the same as ENROLLMENT ID.

ORGANIZATION TYPE STRUCTURE: This describes the recorded enrollment's admitted healthcare facility's business structure.

ORGANIZATION OTHER TYPE TEXT: If the recorded enrollment's admitted healthcare facility in the record has a secondary business structure, it will be contained here.

PROPRIETARY_NONPROFIT: This shows whether the recorded enrollment's admitted healthcare facility is for-profit, non-profit or another option.

CITY: This is the City where the recorded enrollment was conducted.

DATE: The month and year the record was taken.

In [54]:
df_snf_facility2.head()

,CMS Certification Number (CCN),Provider Name,City/Town,State,Ownership Type
0,015009,"BURNS NURSING HOME, INC.",RUSSELLVILLE,AL,For profit - Corporation
1,015010,COOSA VALLEY HEALTHCARE CENTER,SYLACAUGA,AL,For profit - Corporation
2,015012,HIGHLANDS HEALTH AND REHAB,SCOTTSBORO,AL,Government - County
3,015014,EASTVIEW REHABILITATION & HEALTHCARE CENTER,BIRMINGHAM,AL,For profit - Individual
4,015015,PLANTATION MANOR NURSING HOME,MC CALLA,AL,For profit - Corporation

In [55]:
df_hospice_facility2.head()

,CMS Certification Number (CCN),Facility Name,City/Town,State,Ownership Type
0,001500,AGAVE HOSPICE AND PALLIATIVE CARE,PHOENIX,AZ,For-Profit
1,001502,"FAMILY FIRST HOSPICE, INC",PHOENIX,AZ,For-Profit
2,001504,"VITAL HC, INC",MESA,AZ,For-Profit
3,001505,ADVOCATE HOSPICE,PHOENIX,AZ,For-Profit
4,001508,OPTIMAL HOSPICE INC,TEMPE,AZ,For-Profit

CMS Certification Number (CCN): This shows the the unique certification ID of the recorded facility.

Facility Name/Provider Name: This shows the name of the recorded facility.

City/Town: This shows the city location of the recorded facility.

State: This shows the state location of the recorded facility.

Ownership Type: This shows the profit status of the recorded facility.

#### Beneficiary Dictionary

In [56]:
df_medicare_benes4.head()

  STATE_ABV BENE_STATE_DESC  YEAR  TOT_BENES
0        AK          Alaska  2025   121911.0
1        AL         Alabama  2025  1133045.0
2        AR        Arkansas  2025   687541.0
4        AZ         Arizona  2025  1536462.0
5        CA      California  2025  7130161.0

STATE_ABV: This shows the US state in it's abreviated form. (Texas = TX, California = CA, etc...)

BENE_STATE_DESC: This shows the US state.

YEAR: This shows the year the record was taken.

TOT_BENES: This shows the total number of Medicare beneficiarie in the specified state as of October 2025.

#### Population Dictionary

In [57]:
df_state_population4.head()

          STATE  POPULATION STATE_ABV
0    California  39355309.0        CA
1         Texas  31709821.0        TX
2       Florida  23462518.0        FL
3      New York  20002427.0        NY
4  Pennsylvania  13059432.0        PA

STATE: This shows the US state.

POPULATION: This shows the total number of people in the specified state as of July 2025.

STATE_ABV: This shows the US state in it's abreviated form. (Texas = TX, California = CA, etc...)